### ISSUE TITLE
How can we get the data.gov.uk URL of a dataset?

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#10]
It would be nice to have the link to data.gov.uk page if it exists on our resource / asset landing page.

This could be tricky.... The current plan is to (logically at least) publish to the Datahub first, then DGU. 
- Is the data.gov.uk URL conventional or calculable?

Needs investigation. Could fundamentally affect the publishing mechanism design.

**Comment by owenboswarva** [comment]
On the current DGU platform the URL isn't calculable. There's a GUID assigned by DGU as part of the URL but it has no correspondence to our GUIDs. (On the old platform the DGU URL was guessable from the dataset title, although not with complete reliability.)

**Comment by PeteMontgomery** [comment]
We realised we don't need this. DGU pages link to Hub.
