### ISSUE TITLE
Set up monitoring/alerts on the Q 

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/datahub#104]

**Comment by LynnHeeley** [comment]
requires completing before live

**Comment by mattdebont** [comment]
Added monitoring to AWS SQS service, alerts Cathy / Me when the dead letter queue has one or more value added to it in a 5 minute which comes from failures in the Lambda function

**Comment by mattdebont** [comment]
Alerts not firing again, needs re-investigation

**Comment by CathyJinJNCC** [comment]
This should be fixed now by changing the metric it's alerting on. Also added Pete, Felix, and Jon as subscribers.
