### ISSUE TITLE
Abstract contains markdown 

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/datahub#118]
The Abstract (in particular) in a Topcat record has paragraph breaks - when published to the ResourceHub these paragraph breaks do not appear.

**Comment by jonparsonsjncc** [comment]
possible duplicate
jon to check
see if ulric is ok to close

**Comment by jonparsonsjncc** [comment]
here is the record in topcat
http://topcat/app/#/editor/4073feba-5a2f-4fe9-9682-ea098c84d73f
here is the record on the hub
https://hub.jncc.gov.uk/assets/4073feba-5a2f-4fe9-9682-ea098c84d73f
@CathyJinJNCC can we discuss if it is appropriate to add code in to these fields

**Comment by jonparsonsjncc** [comment]
Cathy send all data through with urls
jon to re educate editors
