### ISSUE TITLE
Deploy and demo of sitemap

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/datahub#119]
- review the comments in the pull request
- jenkins job to regenerate datahub sitemap
- discuss and changes
- demo /knowledge share to team

**Comment by mattdebont** [comment]
Working on pull request datahub/pull/115

**Comment by mattdebont** [comment]
Most of this ticket is now finished, just needs a handover to the other devs on how it works under the hood as its another thing on the pile of stuff to make the datahub work. Deployment / Invocation can be done via Jenkins jobs now

**Comment by mattdebont** [comment]
Waiting on dev handover

**Comment by mattdebont** [comment]
Demo'd to devs, waiting full deployment to test further
