### ISSUE TITLE
Add published date for the SAC resources

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#135]
Currently we don’t have a published date for the SAC resources, there isn’t one in the source database, so I need to figure out a way for a user to supply a tranch date to the process so that published dates can be updated in the search results.

**Comment by jonparsonsjncc** [comment]
Jon to discuss with Ulric

**Comment by jonparsonsjncc** [comment]
add date from csv file
also add into main database
stuart to  look at first

**Comment by jonparsonsjncc** [comment]
[https://app.zenhub.com/files/132160057/eac3472b-efd4-4e63-bdca-51960042972d/download](https://app.zenhub.com/files/132160057/eac3472b-efd4-4e63-bdca-51960042972d/download)

Hi @felixMasonJncc see file attached from stuart with the Designation date as the published date

Could you deploy and update the search

thanks

Jon

**Comment by felixMasonJncc** [comment]
Have run in the data as requested 

If you search for a sac in the above file by title you should see that the publication date for the pdf matches that given in the spreadsheet

eg River Wensum = 16/03/2001 which appears as  2001-03-16 in the search results

(NB: I ran this into beta initially to check data integrity and then into live)
