### ISSUE TITLE
Add google analytics and tag manager to data hub

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#138]
I though the analytics was in place for this as there was an account created - but it was not recording any data - and checking the site there is no code added

so please find details below

[https://app.zenhub.com/files/132160057/b924f5d8-1428-4287-9b59-dcd6b1751da4/download](https://app.zenhub.com/files/132160057/b924f5d8-1428-4287-9b59-dcd6b1751da4/download)

and code below for tag manager

[https://app.zenhub.com/files/132160057/199fed05-6652-4fe8-a102-45528dce39a3/download](https://app.zenhub.com/files/132160057/199fed05-6652-4fe8-a102-45528dce39a3/download)

**Comment by PeteMontgomery** [comment]
Just put both these snippets into the live env.

**Comment by PeteMontgomery** [comment]
Just let me know if there's anything else to do. I removed the existing GTM code that was there and added the bits you requested - only on the live env.
