### ISSUE TITLE
Design hub home page

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#140]
see attached document highlighting changes to the hub [https://app.zenhub.com/files/132160057/64798ff4-4242-4ba2-8f80-48a5d130a96b/download](https://app.zenhub.com/files/132160057/64798ff4-4242-4ba2-8f80-48a5d130a96b/download)

The 2 featured publications and 2 featured data sets are to be manually administered within a hosted JSON file
Similarly for the home page text

The categories also need to be manually added as they are a small selection so also need to be edited through the JSON file - together with the description text for each of the categories

Hope this helps

**Comment by PeteMontgomery** [comment]
Moved to beta

**Comment by jonparsonsjncc** [comment]
Hi @PeteMontgomery 
thanks for this on the beta site http://datahub-beta.eu-west-1.elasticbeanstalk.com/

please find attached screen shot highlighting the categories to use for the bottom of the page
![cat.PNG](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/176d3bb5-0b59-41ab-8fe3-7be1a8f267a9)

please use the text for each as shown on the image
for the missing EO text please use
A collection of different mapping outputs using Earth Observation data

**Comment by jonparsonsjncc** [comment]
please use these two pages for the time being as featured publications
https://hub.jncc.gov.uk/assets/4073feba-5a2f-4fe9-9682-ea098c84d73f
https://hub.jncc.gov.uk/assets/328bf8f3-f1e9-499c-80a5-0ecc81fd7334

and these two pages for the featured data

https://hub.jncc.gov.uk/assets/e2a46de5-43d4-43f0-b296-c62134397ce4
https://hub.jncc.gov.uk/assets/d6381e39-baa4-4f12-93d7-fa16dd3600b8

all are examples for the time being until I get a better list

**Comment by jonparsonsjncc** [comment]
Could you also please update the footer with the links from 
http://edit-website/

**Comment by jonparsonsjncc** [comment]
also could you add this text to the home page header

Resource Hub

Welcome to the JNCC Resource Hub – our online portal that allows you to explore, download and reuse our corporate, technical and scientific information.   

In support of our commitment to open access data we produce a broad range of reports and other types of publication, plus an array of datasets. This is part of our commitment to our customers, who include governments, public and private sector organisations and NGOs.

Explore our resources and data products here….

**Comment by jonparsonsjncc** [comment]
this text also needs to be placed on the about us page

About us

JNCC is the public body that advises the UK Government and devolved administrations on UK-wide and international nature conservation. We provide evidence, information and advice so that decisions are made that protect natural resources and systems. We work on nature conservation issues that affect the UK and internationally.

with a button link to http://jncc.gov.uk/about-jncc/ to find out more
