### ISSUE TITLE
Search results in live site have incorrect URLs

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#141]
I have just searched for west wales on the live site
http://pre-live.jncc.gov.uk/search?q=west+wales
And lots of relevant pages are found
but the url link from each entry doesnt link to the page - it has this link
http://pre-live.jncc.gov.uk/search?q=west+wales#

presuming this is related to the issue you are noticing - but from what i can see the index entry is there but the url isnt

**Comment by CathyJinJNCC** [comment]
I think this is an issue on the website side. I can see in the logs the messages we're getting sent are missing the URL as shown below.

{
    "verb": "upsert",
    "index": "live-web",
    "document": {
        "id": 1549,
        "site": "website",
        "title": "Offshore MPAs",
        "content": "This page provides links to Site Information Centres which have been developed for designated offshore MPAs in the UK. Information about MPAs located in both territorial and offshore waters is available on the JNCC interactive map. Add link to interactive map\nTo access the Site Information Centres, please click on the relevant link below:\n\n\n\nAnton Dohrn Seamount SAC\nNorth Norfolk Sandbanks and Saturn Reef SAC\n\n\nBassurelle Sandbank SAC\nNorth-West Orkney NCMPA\n\n\nBraemar Pockmarks SAC\nNorth-West of Jones Bank MCZ\n\n\nBristol Channel Approaches SAC\nNorth-West Rockall Bank SAC\n\n\nCentral Fladen NCMPA\nNorwegian Boundary Sediment Plain NCMPA\n\n\nCroker Carbonate Slabs cSAC/SCI\nOffshore Brighton MCZ\n\n\nDarwin Mounds SAC\nOffshore Overfalls MCZ\n\n\nDogger Bank SAC\nOuter Thames Estuary SPA\n\n\nEast of Gannet and Montrose Fields NCMPA\nPisces Reef Complex SAC\n\n\nEast of Haig Fras MCZ\nPobie Bank Reef SAC\n\n\nEast Rockall Bank SAC\nRosemary Bank Seamount NCMPA\n\n\nFarnes East MCZ\nScanner Pockmark SAC\n\n\nFaroe-Shetland Sponge Belt NCMPA\nSkomer, Skokholm and the Seas off Pembrokeshire SPA\n\n\nFirth of Forth Banks Complex NCMPA\nSolan Bank Reef SAC\n\n\nFulmar MCZ\nSouthern North Sea SAC\n\n\nGeikie Slide and Hebridean Slope NCMPA\nSouth Dorset MCZ\n\n\nGreater Haig Fras MCZ\nSouth-West Deeps (West) MCZ\n\n\nGreater Wash SPA\nStanton Banks SAC\n\n\nHaig Fras SAC\nSwallow Sand MCZ\n\n\nHaisborough, Hammond and Winterton SAC\nThe Barra Fan and Hebrides Terrace Seamount NCMPA\n\n\nHatton Bank cSAC\nThe Canyons MCZ\n\n\nHatton-Rockall Basin NCMPA\nTurbot Bank NCMPA\n\n\nInner Dowsing, Race Bank and North Ridge SAC\nWest Shetland Shelf NCMPA\n\n\nIrish Sea Front SPA\nWest of Walney MCZ\n\n\nLiverpool Bay SPA\nWest Wales Marine SAC\n\n\nNorth-east Faroe-Shetland Channel NCMPA\nWestern Channel MCZ\n\n\nNorth Anglesey Marine SAC\nWight-Barfleur Reef SAC\n\n\nNorth Channel SAC\nWyville Thomson Ridge SAC\n\n\nNorth East of Farnes Deep MCZ\n \n\n\n\nSpecial Areas of Conservation – cSACs/SCIsOffshore candidate SACs (cSACs) have been notified to the European Commission as Sites of Community Importance under Section 7 of the Conservation of Offshore Marine Habitats and Species Regulations 2017, in order to protect habitats and species of European importance. More information about offshore SACs and the site selection process is available on the Marine SAC pages.\nSpecial Protected Areas – SPAsThere are five Special Protected Areas with marine components where either a small proportion of the site or the entire site is in offshore waters. More information about SPAs with marine components is available on the Marine SPA pages.\nNature Conservation MPAs – NCMPAsThese MPAs have been designated in waters around Scotland for nationally important marine wildlife, habitats, geology and geomorphology. They are a national designation introduced under the Marine and Coastal Access Act (2009) (for offshore waters) and the Marine (Scotland) Act (2010) (for territorial waters). More information about NCMPAs and the site selection process is available on the Nature Conservation MPA pages.\nMarine Conservation Zones - MCZsMCZs are a national designation introduced under the Marine and Coastal Access Act (2009), and have been designated in English territorial waters, and UK offshore waters around England, Wales and Northern Ireland for nationally important marine wildlife, habitats, geology and geomorphology. More information about MCZs and the site selection process is available on the Marine Conservation Zone pages.\nMPAs in territorial waters\nInformation on MPAs in territorial waters (0-12 nautical miles) is available via the links to the Statutory Nature Conservation Body websites:\n\nEngland – Natural England\nScotland – Scottish Natural Heritage\nWales – Natural Resources Wales\nNorthern Ireland – Department of the Environment\r\nnull",
        "url": "#",
        "published_date": "2019-06-12"
    }
}

**Comment by jonparsonsjncc** [comment]
See attached list of all pages contained in the live site at the moment - if this helps gives you a list to compare with against the index[https://app.zenhub.com/files/132160057/26b226a2-230c-4f20-be39-163a838306dd/download](https://app.zenhub.com/files/132160057/26b226a2-230c-4f20-be39-163a838306dd/download)
