### ISSUE TITLE
Create a 404 page for data.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#147]
as this will be a public facing url from the hub.jncc.gov.uk site
there should be some presence visually if anyone trys to look to the root
so we do need a single page site creating
see attached page design to follow

[https://app.zenhub.com/files/132160057/982dd49a-4a1e-4028-846e-659100fc4e63/download](https://app.zenhub.com/files/132160057/982dd49a-4a1e-4028-846e-659100fc4e63/download)

related to this we also need to create a 404 page to more sensitively handle URL to files which have been removed - see design attached

[https://app.zenhub.com/files/132160057/85dd2dec-d847-4d5b-a571-d1c55ca879b9/download](https://app.zenhub.com/files/132160057/85dd2dec-d847-4d5b-a571-d1c55ca879b9/download)

**Comment by mattdebont** [comment]
Basic design of this + homepage are done, under _index.html and _404.html for verfication, will switch them to the correct config / place when the website starts going live

Needs some text for the home page, the 404 page is the standard text with the resource hub search attached, no analytics are applied to this server

**Comment by mattdebont** [comment]
Have created 500 / 400 / 404 error pages and the home page, pushed to live now

**Comment by mattdebont** [comment]
Waiting for go live before making pages default for now
