### ISSUE TITLE
Add content to meta description field

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#148]
To help prescribe to google the data to use in the description field in the SERPs - see attached document showing the content on the page which will be better to use

[https://app.zenhub.com/files/132160057/2c6e29c4-20b0-4035-9548-89e5ec8e3b3b/download](https://app.zenhub.com/files/132160057/2c6e29c4-20b0-4035-9548-89e5ec8e3b3b/download)

please duplicate this text field for each page into the meta description field - and limit it to 160 characters

**Comment by jonparsonsjncc** [comment]
To confirm if complete

**Comment by PeteMontgomery** [comment]
Yes, this was done.
