### ISSUE TITLE
Responsible Organisation label should be carefully worded to avoid taking ownership

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#15]
We don't want to appear to accidentally claim ownership of something which isn't ours. The Topcat label of Responsible Organisation / Author is not appropriate. Something like:

**Organisation**
JNCC *Distributor*
data@jncc.gov.uk

**Comment by PeteMontgomery** [comment]
![image](https://user-images.githubusercontent.com/917606/52207007-f6e40700-2873-11e9-9bfd-a9bd417d1408.png)

I've tried just 'Organisation' for the label and it's confusing. This is a Gemini field name - all the others are Gemini field names too - so it's a very standard phrase. I've made the `role` (in this case `distributor`) is clearly visible so **I don't think that this implies any ownership**.  

Please could you comment @owenboswarva @ulric-wilson ? I'd like to close this one if possible.

**Comment by owenboswarva** [comment]
I don't share this concern. The existing label is fine.

**Comment by PeteMontgomery** [comment]
Thanks @owenboswarva . @ulric-wilson @mattdebont I can't remember where this concern came from? Unless someone comments I shall close at the end of the sprint.
