### ISSUE TITLE
Visualisation of LAS data layers

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#161]
Create in map visualisation of LAS data layers

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont 
we have been sent some data to possibly help

message from Lynn

Gdb with footprints for DSM at least in there for phase 1 and phase 2 lidar.
You can use the ‘PRODUCTNAME’ field to distinguish between the surveys and the ‘CAPTURE DATE’ attribute may be of use for metadata enquiries.  

Not sure whether this will be useful/what we want but was worth asking in case….
Lynn

Location of the file 
Z:\Prog110-FutureData\JNCC Websites\Lidar Scottish remote sensing data

**Comment by mattdebont** [comment]
That file is worse than what we have already, its just a 10k (phase-2) or 1k (phase-1) map, there are other paths we would go down which are a better use of our time really. 

The only useful part of that could be the capture date stuff in the future but we don't have a way of surfacing that anyway and it wasn't a requirement as far as I was aware. The issue there being that I am fairly sure that at least some of the 10k blocks would have been covered over multiple days and there is no way to surface that info for the Phase-2 data so you are providing a date but we aren't sure what that applies to in the tiles in this case.

Same issue applies to a lesser extent to the phase-1 data, to get the best info out of that you would need the exact flight capture information for each pixel (can be amalgamated into polygons) but then we would need a way of showing that data somehow to the end users. 

So more a box I wouldn't want to open up if it can be avoided.
