### ISSUE TITLE
Ensure top cat renders markdown in the same way as the hub

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#173]
ie

at present with headings in top cat both these syntax are correct

####heading and #### heading ie with and without the sapce

but in the hub only this version  #### heading with the spaces actually renders correctly - as this is the correct syntax

the problem is if ####heading is used it is not recognised in the hub as displays as plain text

we need to align the top cat display of markdown to be the same as the hub so this is highlighted to the user as an error before publishing

**Comment by felixMasonJncc** [comment]
There are a couple of issues here.

* Datahub users the [westwind markdown renderer.] (https://github.com/RickStrahl/Westwind.AspNetCore.Markdown) This is available only on .net core
* Topcat uses [Showdown](https://github.com/showdownjs/showdown) which is a javascript based markdown renderer.
* Its not obvious how to disable title rendering in showdown.
* Its probably possible to configure the flavours of markdown that westwind responds to to enable it to render titles in the same way as showndown - maybe.
* Showdown could be implemented in the datahub with a bit  of reworking of the page (rendering would be client rather then server side.
* To get showndown to not render titles at all would probably mean intercepting the data that's typed in and stripping out titles dynamically

* None of this is worth the effort - Titles are a result of an import not users putting them in for the most part.
