### ISSUE TITLE
hub.jncc.gov.uk is missing its 404 page

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#176]

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont 
Could you pick this up please
bearing in mind the hub will be coming in line with the main website
it would be best to follow the 404 design of the main website

**Comment by mattdebont** [comment]
Deployed to beta for testing

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont - happy for you to deploy this to live

**Comment by mattdebont** [comment]
@jonparsonsjncc  Deployed to live, but there is an additional requirement, would probably need to hook 404 onto bad asset id's as well, currently it throws and error page but probably should throw a 404

**Comment by mattdebont** [comment]
@jonparsonsjncc have pushed a 404 error page onto not found asset pages, on beta if you want to check
