### ISSUE TITLE
Migration of the hub's load balancer - Matt

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#185]
at some point we need to schedule in a migration for the hub's load balancer from classic->application as that will eventually be forced from the aws side, would rather we scheduled the change than wait for it to be migrated for us

thats the only load balancer that will survive when the Scottish lidar portal is migrated, all the others should dissapear

Time required
it should just be hit migrate and wait, the time scheduled is there to pick it up if it goes wrong
we may have to rebuild the hub environment in the worst case
which may take a day or so if it goes very wrong
its not something that we need to decide soon soon, but will need to be on the radar of things to do

notes
ok had a quick read, suggested migration pattern is recreate the elasticbeanstalk environment and then switch DNS entries when ready by the looks of things
the load balancer migration works fine, but if its tied to elasticbeanstalk, it will try and recreate stuff

**Comment by mattdebont** [comment]
General plan at present recreate elasticbeanstalk environment with new load balancer when development is active again and update Jenkins deployment to point to the new environment, then swap the DNS entry when its ready then retire the old environments
