### ISSUE TITLE
Create new search results page for the JNCC website - Cathy

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#203]
To implement a new search results page for the JNCC website as part of the hub site

See visuals attached

**Product breakdown structure**https://app.zenhub.com/files/132160057/c7696a70-0070-4e0a-bfd5-07354074528e/download

Qs
- What to do with URL resources? e.g. on the hub, search "web map service". A: For now get them to point back to the asset page. In a later phase of work we can give them proper anchor links like for the file links.
- What to do with hub assets with no resources? (technically possible but probably no examples of it) Do they just not show up in any searches? A: These will show up under the resources tab and point to the asset page.
- What to do about hub query page/related pages functionality in the CMS? At the moment content editors can do a search as usual in the hub, edit the url to point to the "query" endpoint (e.g. https://hub.jncc.gov.uk/query?q=sea) and then copy and paste the contents of that (the elasticsearch query object) into an umbraco widget, built by carbon 6, that directly queries elasticsearch and displays the results. We want search requests to be done through our gateway; no other services should be able to directly query elasticsearch (to try to avoid extra unnecessary credentials + search logic in multiple codebases). A: We will leave it as it is for now because there are questions of tying this into the keyword search, which ties into the issue of keyword management/curation and having a central vocab service.
  - If we leave it as is, the underlying documents still change so the results will be different (no asset pages). Q: Is this fine? Yes, Jon will remove use of the related datahub pages functionality
- If we don't have functionality for keyword searches on the new search page, how will we handle the search links from the datahub assets pages and the datahub front page? A: Remove/hide the keyword search functionality on the datahub for now.

Phase 2 (notes for future work)
- Domain name change?
  - Change hub.jncc.gov.uk to be resources.jncc.gov.uk 
  - Scan for and update hub links where possible in content of JNCC website, MHC, SAC, etc
  - Change hub links on website template and apply to all microsites/data.jncc
  - Implement redirects
  - top cat publishing changes
    - Update hub.jncc.gov.uk references to resources.jncc.gov.uk
    - Maybe do a bulk republish to update all the gov.uk links that point back to the hub asset pages?
  - Re index datahub pages to populate search results with correct links
- Anchor links for web resources (see datahub#215 and datahub#216)
  - Change the datahub ingester to set the URL to the anchor link for web resources + reindex (maybe save the webified name in dynamo)
  - Change the datahub UI to do the anchor highlight functionality with web resources
- Related pages/resources querying
  - Need to set up API for the website to query (might already be set up but might need tweaking)
  - Need carbon 6 to update the CMS widget thing to not directly query elasticsearch and go through the API instead
  - Remove the "query" page from datahub, and remove logic around direct elasticsearch searching
  - Get carbon 6 to remove the direct elasticsearch querying logic from the website

**Comment by CathyJinJNCC** [comment]
Current index doc examples
![current index docs.png](https://images.zenhubusercontent.com/596f7cf061b4ca3b0a74fdc5/12150350-c5d0-4477-a436-33f77b32e83f)

Proposed changes
![changes for new search.png](https://images.zenhubusercontent.com/596f7cf061b4ca3b0a74fdc5/a269ed26-c893-4ea8-b27f-fab898a5c4dd)

**Comment by jonparsonsjncc** [comment]
Hi @CathyJinJNCC - See new visual attached highlighting approach for web links, non asset entries and the key for the filter panel
[https://app.zenhub.com/files/132160057/c7696a70-0070-4e0a-bfd5-07354074528e/download](https://app.zenhub.com/files/132160057/c7696a70-0070-4e0a-bfd5-07354074528e/download)

**Comment by CathyJinJNCC** [comment]
Closing this, use https://app.zenhub.com/workspaces/dev-board-59b7d1ba3d598a066f875855/issues/jncc/dev/364 for tasks now
