### ISSUE TITLE
Update content on hub landing page - Cathy

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/datahub#232]
Please see attached document
[https://app.zenhub.com/files/132160057/fde0a1f5-84ac-46cd-bd29-0f0679620d88/download](https://app.zenhub.com/files/132160057/fde0a1f5-84ac-46cd-bd29-0f0679620d88/download)
The changes arent possible in the code by changing the words

could you make the proposed structural changes please

Jon

**Comment by CathyJinJNCC** [comment]
In beta, waiting for go ahead to deploy to live

**Comment by CathyJinJNCC** [comment]
Deployed
