### ISSUE TITLE
Update links in footer (Terms/Privacy/Contact us)

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#4]
Plan is to use the main website page. Link to from the footer.

We don't think there' anything else to do really.

**Comment by mattdebont** [comment]
Ticket is done as far as we can at this point as far as we can do it for now, we need to get the real location for these links, just need to update the footer for all resources

**Comment by LynnHeeley** [comment]
location required to link to

**Comment by jonparsonsjncc** [comment]
Closing as done as part of 
https://app.zenhub.com/workspaces/dev-board-59b7d1ba3d598a066f875855/issues/jncc/datahub/140
