### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#48]
Matt has a new deployment mechanism to replace Felix's - but it needs to be automated.

**The full steps to manually deploy are now in the readme.md** but this is still a manual process.

**Comment by mattdebont** [comment]
Deploy to ECR

Ensure you have installed the latest version of the AWS CLI and Docker. For more information, see the ECR documentation .

    Retrieve the login command to use to authenticate your Docker client to your registry.
    Use the AWS CLI:

    $(aws ecr get-login --no-include-email --region eu-west-1)

Note: If you receive an "Unknown options: --no-include-email" error when using the AWS CLI, ensure that you have the latest version installed. Learn more 
Build your Docker image using the following command. For information on building a Docker file from scratch see the instructions here 
. You can skip this step if your image is already built:

docker build -t jncc-datahub-web .

After the build completes, tag your image so you can push the image to this repository:

docker tag jncc-datahub-web:latest 914910572686.dkr.ecr.eu-west-1.amazonaws.com/jncc-datahub-web:[TAGNAME]

Run the following command to push this image to your newly created AWS repository:

docker push 914910572686.dkr.ecr.eu-west-1.amazonaws.com/jncc-datahub-web:[TAGNAME]

**Comment by PeteMontgomery** [comment]
The second step is to run eb commands to upload the little json file to EB that points to the image. The image will need to be tagged with git version. The security stuff will need to be enabled so that the AWS Jenkins can access ECR and EB, I guess.
