### ISSUE TITLE
Ingest a large pdf to measure time taken / investigate local text extraction to get round 10MB payload problem

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/datahub#52]
test other document types to check performance

**Comment by mattdebont** [comment]
There is a 10MB payload limit for files into elasticsearch so we will need to figure out an alternative path for these via topcat.robot most likely

**Comment by PeteMontgomery** [comment]
WRT to doing the parsing in Tika in the AWS Lambda. Worth noting:
> If you are using Amazon Simple Queue Service as an event source, make sure the value of the function's expected execution time does not exceed the Visibility Timeout value on the queue.

**Comment by mattdebont** [comment]
Have a working example of Java/Tika parsing function in the elasticsearch-lambda-ingester repository, currently pushing 10MB document through it with no issue. Have attempted to make a switch that only parses in the lambda when payload > 10MB but having some issues with the pipeline and the content_base64 field

**Comment by mattdebont** [comment]
Still and issue with a >10MB payload after text extraction, but thats a fairly limited problem as far as I can see. It will just error out when processing if it happens so we will see it happening and should be able to fix as necessary

**Comment by mattdebont** [comment]
Example large files Z:\Prog110-FutureData\0077 Website development\planning\JNCC website shared folder 2018\DataHub_Microsites\Example large files

**Comment by mattdebont** [comment]
It looks like any one field can have a maximum of size of 32766 bytes in Lucene (powers elasticsearch). We can potentially bypass this by making the content field an array and having 32766 byte chunks of data in each array item.

32kb of pure text roughly equivalent to 20 pages of text so it should be good enough to begin with, we can revisit this issue later if it becomes an issue however.

**Comment by mattdebont** [comment]
Have moved on, can ingest v. large circa 1300 page documents reasonably easily, had to modify the index to use fast vector highlighters to speed up large document highlighting (plain highlighting was taking multiple seconds fvh is more reasonable)
