### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#56]
To enable Google etc. to search, we need to generate a sitemap, or a least a browse, so that every asset is reachable from the homepage.

**Comment by mattdebont** [comment]
1. Calculate sitemap.xml on request;
    - Always up to date with latest in database
    - Table scan dynamodb and create xml on request
        - Trivial attack vector
            - Can force us to spend time re-generating xml over and over again, forcing us to scale up for robot scans of the system (there are many)
        - It doesn't change apart from uploads so this is wasted, need to cache
 2. Update sitemap.xml as part of upload
    - 1 to 1 operation, simple to understand in principle
    - What happens with manual deletes? Need another chain to handle removing entries from the hub manually
    - Updates many times per ingested asset 
 3. Calculate and cache sitemap statically
    - Daily sitemap update at x time
    - Cache result to S3
    - Run from DynamoDB or Elasticsearch
        - arguably dynamodb is the better place for this, start from single source of truth, if something is in dynamodb it is 'published' no matter if its in the search results or not
    - use published since last run? to reduce complexity?
        - what about manual deletes again?
    - https://medium.com/vevo-engineering/scalable-sitemap-solutions-with-aws-lambda-js-fd926c861c0d
        - lambda job to update the sitemap, run daily? at x in the morning
            - retireve all datahub assets
                - for each asset add to sitemap-assets.xml
                - for each resource in asset add to sitemap-resources.xml
                - store in s3? have the app just front this delivery?
                - update sitemap.xml to point to these (up to 50,000 records / 50MB) per file as per https://www.sitemaps.org/protocol.html#index should be fine to deal with compressed here so only real limit is likely the 50000 records potentially

**Comment by mattdebont** [comment]
robots.txt =>
```
user-agent: *
disallow: /
sitemap: https://hub.jncc.gov.uk/sitemap.xml
```
        
sitemap.xml =>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>http://www.example.com/sitemap-assets.xml.gz</loc>
      <lastmod>2019-04-01T03:00:00+00:00</lastmod>
      <changefreq>daily</changefreq>
   </sitemap>
   <sitemap>
      <loc>http://www.example.com/sitemap-resources.xml.gz</loc>
      <lastmod>2019-04-01T03:00:00+00:00</lastmod>
      <changefreq>daily</changefreq>
   </sitemap>
</sitemapindex>
```

sitemap-assets.xml.gz / sitemap-resources.xml.gz =>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://hub.jncc.gov.uk/asset/xxxx-xxxxxx-xxxxxxx-xxxxx</loc>
      <lastmod>2019-04-01T03:00:00+00:00</lastmod>
      <changefreq>monthly</changefreq>
   </url>
   ....
</urlset> 
```

**Comment by jonparsonsjncc** [comment]
Pete to merge

**Comment by PeteMontgomery** [comment]
@jonparsonsjncc, @mattdebont has pushed this live - please check https://hub.jncc.gov.uk/sitemap.xml

**Comment by jonparsonsjncc** [comment]
Looks the correct format

But there are only 6 pages shown and the site has a lot more than this

Also the individual pdfs are not shown in it or the about us page, search page etc

Please advise
