### ISSUE TITLE
Live environment

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/datahub#66]
- [x] Create a live environment on Elastic Beanstalk
- [x] Use AWS SSL management 
- [x] Use IAM to restrict the live env to JNCC only
- [ ] Ensure / investigate SSL stuff is appropriate (e.g. HSTS header - speak to Matt)
- [x] Add CNAME to jncc DNS
- [x] The live URL will be https://hub.jncc.gov.uk/

I created a working `datahub-live` EB environment to replace the 'docker-test' one that has been used for development so far. I had to add the correct IAM instance profile in order for Search to work. 

~~We should recreate this with a custom domain name (just like beta)  rather than an auto-generated one however before proceeding further.~~
I've re-created `datahub-live` so should be good to go.

**Comment by PeteMontgomery** [comment]
Created a working `datahub-live` EB environment to replace the 'docker-test' one that has been used for development so far.

**Comment by mattdebont** [comment]
Couple of things to test the SSL status of the site when it goes live;
https://www.ssllabs.com/ssltest/

Config for web servers / https https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by felixMasonJncc** [comment]
Cheked env setup
Live: 
- DB: datahub-live-assets
- ElasticSearch Index: live-web

Beta:
- DB: datahub-beta-assets
-  ElasticSearch Index: beta
