### ISSUE TITLE
Cookie consent

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#76]
For when user lands straight on the hub. Will need to use same cookie consent as main site.

**Comment by PeteMontgomery** [comment]
@mattdebont has started to look at this one.

**Comment by mattdebont** [comment]
Refine, this use single site spanning cookie control?

**Comment by felixMasonJncc** [comment]
Awaiting css

**Comment by jonparsonsjncc** [comment]
Should this now be applied to all microsites

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont 
could you apply the same cookie consent to 
mhc, sac and hub please

**Comment by jonparsonsjncc** [comment]
Hi @mattdebont 
cookie consent doesnt seem to appear for the hub

it does for mhc and sac
