### ISSUE TITLE
Check that search:run:windows actually works in Windows 

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#79]
Check that 8bdcaf4a2bb73e5d48d7b12bad271c59464e99a8 really works on Windows

**Comment by mattdebont** [comment]
It doesn't work natively, issue is that yarn runs in command prompt rather than powershell by default so its pretty difficulty to make this work, hence why I didn't roll it into yarn in the first place

**Comment by mattdebont** [comment]
its the $(docker build .)  part that command prompt chokes on and the && that powershell chokes on, suggest just do it manually rather than getting yarn to do it

**Comment by PeteMontgomery** [comment]
Thanks @mattdebont. Could you re-open @felixMasonJncc ?

**Comment by LynnHeeley** [comment]
won't fix - work around

**Comment by felixMasonJncc** [comment]
We won't bother with this

**Comment by PeteMontgomery** [comment]
Incidentally fixed in 89b2399753378f63d7dc2d1e4fbf51e7df9eaf8c
