### ISSUE TITLE
Search re-indexing - Cathy, Matt

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#90]
It's not an easy task to re-publish everything from Topcat to the Datahub.

The Datahub could perform a full search index rebuild using only the information in the Dynamo database.

**Comment by jonparsonsjncc** [comment]
needs breaking down into smaller tasks

**Comment by jonparsonsjncc** [comment]
Need to have
Need to find a way to manually envoke an full re index 

nice to have
possibly also set this full re index to run every week as a catch all
but also tie in to the publishing process to add in one new record when published

**Comment by jonparsonsjncc** [comment]
Cathy to work with devs to create sub tasks

**Comment by jonparsonsjncc** [comment]
See attached visual from dev workshop
![Whiteboard_2019_7_18.png](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/8d731969-a2d0-4849-a90f-f9629966b1e0)
